import {
  TESTNET_REGISTRAR_URL,
  TESTNET_INDEXER_URL,
  TESTNET_INDEXER_HEALTH_ALT_URL,
  TESTNET_INDEXER_HEALTH_URL,
  TESTNET_NODE_URL,
  TESTNET_NODE_ALT_URL,
  TESTNET_IPFS_URL,
  TESTNET_SERVER_URL,
  TESTNET_BALANCE_INDEXER_URL,
  TESTNET_MONGODB_URL,
  TESTNET_LOCAL_MONGODB_URL,
  TESTNET_EXPLORER_URL,
  MAINNET_REGISTRAR_URL,
  MAINNET_INDEXER_URL,
  MAINNET_INDEXER_ALT_URL,
  MAINNET_INDEXER_HEALTH_URL,
  MAINNET_INDEXER_HEALTH_ALT_URL,
  MAINNET_NODE_URL,
  MAINNET_NODE_ALT_URL,
  MAINNET_IPFS_URL,
  MAINNET_SERVER_URL,
  MAINNET_BALANCE_INDEXER_URL,
  MAINNET_MONGODB_URL,
  MAINNET_LOCAL_MONGODB_URL,
  MAINNET_EXPLORER_URL,
  STATIC_XBALLOT_DOCS_URL,
  STATIC_XBALLOT_DISCORD_URL,
  STATIC_XBALLOT_TWITTER_URL,
  STATIC_XBALLOT_TELEGRAM_URL,
  STATIC_XBALLOT_MEDIUM_URL,
  STATIC_HEADLINE_TWITTER_URL,
  STATIC_HEADLINE_TELEGRAM_URL,
  STATIC_HEADLINE_GITHUB_URL,
  STATIC_ALGO_PRICE_URL,
  STATIC_ASSET_PRICE_URL,
  STATIC_ASSET_PRICES_URL,
  STATIC_STAMP_URL,
} from './constants';

let local_env = 'mainnet';
let local_db_env = 'remote';

let INDEXER_URL: string;
let INDEXER_ALT_URL: string;
let NODE_URL: string;
let NODE_ALT_URL: string;
let INDEXER_HEALTH_URL: string;
let INDEXER_HEALTH_ALT_URL: string;
let MONGODB_URL: string;
let REGISTRAR_URL: string;
let IPFS_URL: string;
let SERVER_URL: string;
let EXPLORER_URL: string;
let BALANCE_INDEXER_URL: string;
let XBALLOT_DOCS_URL: string;
let XBALLOT_DISCORD_URL: string;
let XBALLOT_TWITTER_URL: string;
let XBALLOT_TELEGRAM_URL: string;
let XBALLOT_MEDIUM_URL: string;
let HEADLINE_TWITTER_URL: string;
let HEADLINE_TELEGRAM_URL: string;
let HEADLINE_GITHUB_URL: string;
let ALGO_PRICE_URL: string;
let ASSET_PRICE_URL: string;
let ASSET_PRICES_URL: string;
let STAMP_URL: string;

const configureURLs = () => {

  const env: string = process.env.CHAIN_ENV || local_env;
  const db_env: string = process.env.DB_ENV || local_db_env;

  if (env === 'testnet') {
    // Testnet
    REGISTRAR_URL = TESTNET_REGISTRAR_URL;
    INDEXER_URL = TESTNET_INDEXER_URL;
    INDEXER_ALT_URL = TESTNET_INDEXER_HEALTH_ALT_URL;
    INDEXER_HEALTH_URL = TESTNET_INDEXER_HEALTH_URL;
    INDEXER_HEALTH_ALT_URL = TESTNET_INDEXER_HEALTH_ALT_URL;
    NODE_URL = TESTNET_NODE_URL;
    NODE_ALT_URL = TESTNET_NODE_ALT_URL;
    IPFS_URL = TESTNET_IPFS_URL;
    SERVER_URL = TESTNET_SERVER_URL;
    BALANCE_INDEXER_URL = TESTNET_BALANCE_INDEXER_URL;
    EXPLORER_URL = TESTNET_EXPLORER_URL;
    if (db_env === 'remote') {
      MONGODB_URL = TESTNET_MONGODB_URL;
    } else if (db_env === 'local') {
      MONGODB_URL = TESTNET_LOCAL_MONGODB_URL;
    }
  } else if (env === 'mainnet') {
    // Mainnet
    REGISTRAR_URL = MAINNET_REGISTRAR_URL;
    INDEXER_URL = MAINNET_INDEXER_URL;
    INDEXER_ALT_URL = MAINNET_INDEXER_ALT_URL;
    INDEXER_HEALTH_URL = MAINNET_INDEXER_HEALTH_URL;
    INDEXER_HEALTH_ALT_URL = MAINNET_INDEXER_HEALTH_ALT_URL;
    NODE_URL = MAINNET_NODE_URL;
    NODE_ALT_URL = MAINNET_NODE_ALT_URL;
    IPFS_URL = MAINNET_IPFS_URL;
    SERVER_URL = MAINNET_SERVER_URL;
    BALANCE_INDEXER_URL = MAINNET_BALANCE_INDEXER_URL;
    EXPLORER_URL = MAINNET_EXPLORER_URL;
    if (db_env === 'remote') {
      MONGODB_URL = MAINNET_MONGODB_URL;
    } else if (db_env === 'local') {
      MONGODB_URL = MAINNET_LOCAL_MONGODB_URL;
    }
  }

  XBALLOT_DOCS_URL = STATIC_XBALLOT_DOCS_URL;
  XBALLOT_DISCORD_URL = STATIC_XBALLOT_DISCORD_URL;
  XBALLOT_TWITTER_URL = STATIC_XBALLOT_TWITTER_URL;
  XBALLOT_TELEGRAM_URL = STATIC_XBALLOT_TELEGRAM_URL;
  XBALLOT_MEDIUM_URL = STATIC_XBALLOT_MEDIUM_URL;
  HEADLINE_TWITTER_URL = STATIC_HEADLINE_TWITTER_URL;
  HEADLINE_TELEGRAM_URL = STATIC_HEADLINE_TELEGRAM_URL;
  HEADLINE_GITHUB_URL = STATIC_HEADLINE_GITHUB_URL;
  ALGO_PRICE_URL = STATIC_ALGO_PRICE_URL;
  ASSET_PRICE_URL = STATIC_ASSET_PRICE_URL;
  ASSET_PRICES_URL = STATIC_ASSET_PRICES_URL;
  STAMP_URL = STATIC_STAMP_URL;
};

configureURLs(); // Initial configuration

export const configureNetwork = (network: string) => {
  local_env = network;
  configureURLs(); // Reconfigure URLs when network changes
};

// Export variables
export {
  INDEXER_URL,
  INDEXER_ALT_URL,
  NODE_URL,
  NODE_ALT_URL,
  INDEXER_HEALTH_URL,
  INDEXER_HEALTH_ALT_URL,
  MONGODB_URL,
  REGISTRAR_URL,
  IPFS_URL,
  SERVER_URL,
  EXPLORER_URL,
  BALANCE_INDEXER_URL,
  XBALLOT_DOCS_URL,
  XBALLOT_DISCORD_URL,
  XBALLOT_TWITTER_URL,
  XBALLOT_TELEGRAM_URL,
  XBALLOT_MEDIUM_URL,
  HEADLINE_TWITTER_URL,
  HEADLINE_TELEGRAM_URL,
  HEADLINE_GITHUB_URL,
  ALGO_PRICE_URL,
  ASSET_PRICE_URL,
  ASSET_PRICES_URL,
  STAMP_URL,
};
