// Constants and schemas
import {
  CONST_EXTENDED_SPACE,
  CONST_RANKED_SPACE,
  CONST_PROPOSALS,
  CONST_POSTS,
  CONST_PROFILES,
  CONST_MAIN_JSON,
  CONST_TEST_JSON,
} from './models/constants';

// MONGODB SCHEMAS
import {
  SCHEMA_SPACE,
  SCHEMA_PROPOSAL,
  SCHEMA_PROFILE,
  SCHEMA_PRIME,
  SCHEMA_PORTAL,
  SCHEMA_REPORT,
  SCHEMA_DELEGATE,
  SCHEMA_RANKING,
  SCHEMA_VOTES,
  SCHEMA_FOLLOWERS,
  SCHEMA_PROPOSALS,
} from './models/schemas';

// Import your configuration variables
import {
  INDEXER_URL,
  INDEXER_ALT_URL,
  NODE_URL,
  NODE_ALT_URL,
  INDEXER_HEALTH_URL,
  INDEXER_HEALTH_ALT_URL,
  MONGODB_URL,
  REGISTRAR_URL,
  IPFS_URL,
  SERVER_URL,
  BALANCE_INDEXER_URL,
  EXPLORER_URL,
} from './config';

//import static configuation variables
import {
  XBALLOT_DOCS_URL,
  XBALLOT_DISCORD_URL,
  XBALLOT_TWITTER_URL,
  XBALLOT_TELEGRAM_URL,
  XBALLOT_MEDIUM_URL,
  HEADLINE_TWITTER_URL,
  HEADLINE_TELEGRAM_URL,
  HEADLINE_GITHUB_URL,
  ALGO_PRICE_URL,
  ASSET_PRICE_URL,
  ASSET_PRICES_URL,
  STAMP_URL,
} from './config';

// Import functions

import { configureNetwork } from './config';

// Export constants and schemas
export {
  CONST_EXTENDED_SPACE,
  CONST_RANKED_SPACE,
  CONST_PROPOSALS,
  CONST_POSTS,
  CONST_PROFILES,
  CONST_MAIN_JSON,
  CONST_TEST_JSON,
};

export {
  SCHEMA_SPACE,
  SCHEMA_PROPOSAL,
  SCHEMA_PROFILE,
  SCHEMA_PRIME,
  SCHEMA_PORTAL,
  SCHEMA_REPORT,
  SCHEMA_DELEGATE,
  SCHEMA_RANKING,
  SCHEMA_VOTES,
  SCHEMA_FOLLOWERS,
  SCHEMA_PROPOSALS,
};

// Export your configuration variables
export {
  INDEXER_URL,
  INDEXER_ALT_URL,
  NODE_URL,
  NODE_ALT_URL,
  INDEXER_HEALTH_URL,
  INDEXER_HEALTH_ALT_URL,
  MONGODB_URL,
  REGISTRAR_URL,
  IPFS_URL,
  SERVER_URL,
  BALANCE_INDEXER_URL,
  EXPLORER_URL,
  XBALLOT_DOCS_URL,
  XBALLOT_DISCORD_URL,
  XBALLOT_TWITTER_URL,
  XBALLOT_TELEGRAM_URL,
  XBALLOT_MEDIUM_URL,
  HEADLINE_TWITTER_URL,
  HEADLINE_TELEGRAM_URL,
  HEADLINE_GITHUB_URL,
  ALGO_PRICE_URL,
  ASSET_PRICE_URL,
  ASSET_PRICES_URL,
  STAMP_URL,
};

// Export functions

export { configureNetwork };
