import { ExtendedSpace } from './extendedSpace';

export const Proposals = [
  {
    title: '',
    appId: 0,
    description: '',
    content: '',
    proposalId: 0,
    txnHash: '',
    createdAt: '0',
    voted: true,
    creator: '',
    creatorName: '',
    creatorImage: '',
    id: '',
    ipfs: '',
    ipfsHash: '',
    network: '',
    choices: [''],
    type: '',
    snapshot: '',
    author: '',
    body: '',
    created: 0,
    start: 0,
    end: 0,
    state: '',
    symbol: '',
    privacy: '',
    discussion: '',
    quorum: 0,
    scores: 0,
    scores_state: '',
    scores_total: 0,
    scores_by_strategy: 0,
    votes: 0,
    space: ExtendedSpace,
    strategy: '',
  },
];


export const Posts = [
  {
    title: '',
    description: '',
    content: '',
    postId: 0,
    txnHash: '',
    createdAt: '0',
    voted: true,
    creator: '',
    creatorName: '',
    creatorImage: '',
    id: '',
    ipfs: '',
    ipfsHash: '',
    network: '',
    choices: [''],
    type: '',
    snapshot: '',
    author: '',
    body: '',
    created: 0,
    start: 0,
    end: 0,
    state: '',
    symbol: '',
    privacy: '',
    discussion: '',
    quorum: 0,
    scores: 0,
    scores_state: '',
    scores_total: 0,
    scores_by_strategy: 0,
    votes: 0,
    space: ExtendedSpace,
    strategy: '',
  },
];

export const Proposal = {
    title: '',
    description: '',
    content: '',
    proposalId: 0,
    sender: '',
    senderImage: '',
    txnHash: '',
    createdAt: '0',
    voted: true,
    creator: '',
    creatorName: '',
    creatorImage: '',
    id: '',
    ipfs: '',
    ipfsHash: '',
    network: '',
    choices: [''],
    type: '',
    snapshot: '',
    author: '',
    body: '',
    created: 0,
    start: 0,
    end: 0,
    state: '',
    symbol: '',
    privacy: '',
    discussion: '',
    quorum: 0,
    scores: 0,
    scores_state: '',
    scores_total: 0,
    scores_by_strategy: 0,
    votes: 0,
    space: ExtendedSpace,
    strategy: '',
    strategyType: '',
}

export const Post = {
  appId: 0,
  content: "",
  dataType: "",
  hash:  "",
  id: "",
  sender: "",
  thread: [],
  ticket: {},
  title: "",
  type: ""
}