import React from 'react';
import SpaceProposal from '../SpaceProposal/SpaceProposal';
import SpaceSettings from '../SpaceSettings/SpaceSettings';
import SpaceTreasury from '../SpaceTreasury/SpaceTreasury';
import SpaceAbout from '../SpaceAbout';
import SpaceForum from '../SpaceForum/SpaceForum';
import TreasuryAssetsList from '../SpaceTreasury/TreasuryAssetsList';
import SpaceCreateProposal from '../SpaceCreate/SpaceCreateContent';
import SpaceCreateForumPost from '../SpaceForum/SpaceCreateForumPost';
import SpaceProposals from '../SpaceProposals';
import SpaceForumAbout from '../SpaceForum/SpaceForumAbout';
import DelegateView from 'views/DelegateView/DelegateView';
import { ForumPost } from '../SpaceForum/ForumPost';
import { ThreadPost } from '../SpaceForum/ThreadPost';
import { SubThreadPost } from '../SpaceForum/SubThreadPost';

export const MemoizedSpaceProposal = React.memo(SpaceProposal);
export const MemoizedDelegateView = React.memo(DelegateView);
export const MemoizedSpaceProposals = React.memo(SpaceProposals);
export const MemoizedSpaceAbout = React.memo(SpaceAbout);
export const MemoizedSpaceCreateProposal = React.memo(SpaceCreateProposal);
export const MemoizedSpaceTreasury = React.memo(SpaceTreasury);
export const MemoizedTreasuryAssetsList = React.memo(TreasuryAssetsList);
export const MemoizedSpaceForum = React.memo(SpaceForum);
export const MemoizedSpaceCreateForumPost = React.memo(SpaceCreateForumPost);
export const MemoizedForumPost = React.memo(ForumPost);
export const MemoizedThreadPost = React.memo(ThreadPost);
export const MemoizedSubThreadPost = React.memo(SubThreadPost);
export const MemoizedSpaceForumAbout = React.memo(SpaceForumAbout);
export const MemoizedSpaceSettings = React.memo(SpaceSettings);